### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DeathlyPlays** [HoeenCoder/Wavelength#57]
Lottery:
- [ ] Display Command (/lottery display)
- [ ] Check Time Remaining Command
- [ ] Modify Timer Command
- [ ] Show Current Lottery Prize on display (updates every join silently)

Surveys:
- [ ] Support Shadow Bans filtering answers
- [ ] Support emoticons in surveys

SSBFFA:
- [x] Command that sets/removes the user's custom move/ability/item (so HoeenHero doesn't have to eval it every time)

PSGO:
- [x] Support a /psgo addpack (addcard, etc) and create a joinable storage for so to be shown alongside the cards in `config/cards.json`

**Comment by DeathlyPlays** [comment]
#128 solves the surveys emoticons task

**Comment by DeathlyPlays** [comment]
PSGO addpack done in #165
